linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

run:
  deadline: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  govet:
    shadowing: true
  gofmt:
    simplify: true
  misspell:
    locale: US
